#!/bin/bash
# printf "Which file U need !\n1) main.cpp\n2) mainGL.cpp\nEnter a choice: "
# read choice

main_file="main.cpp" 

# Set main_file to decide Which files to compile
# [ $choice = "1" ] && main_file="main.cpp" || main_file="mainGL.cpp"

# Put here files to be compiled
files_to_compile=(
    "src/InputHandling.cpp"
    "src/DrawingUtilities.cpp"
    "src/$main_file"
)

# the final .exe file 
output_file="main"

compile_command_linux="g++ -o $output_file  -lGL -lGLU -lglut -lXrandr -lXi -lX11 ${files_to_compile[*]} && ./main"
compile_command_windows="g++ -Wall ${files_to_compile[*]} -o $output_file -mwindows glut32.lib  -lopengl32 -lglu32 && ./main"


if [ "$(uname -rs | grep NT)"  ]; then
    # Run Windows command
    echo "Running on Windows. Executing specific command..."
    printf "$compile_command_windows && ./$output_file\n"
    eval  $compile_command_windows
elif [ "$(uname -s)" = "Linux" ]; then
    # Run Linux command
    echo "Running on Linux. Executing another command..."
    printf "$compile_command_linux && ./$output_file\n"
    eval  $compile_command_linux
fi